2025-04-28 03:20:50.753 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 2.7305 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_1(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 81
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:20:50.833 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_1(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 81
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:23:38.147 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 0.1848 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_1(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 81
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:23:38.151 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_1(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 81
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:35:20.779 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 2.4712 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_1(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 81
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:35:20.838 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_1(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 81
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:35:37.341 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 2.6730 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 98
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:35:37.415 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 98
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:37:59.314 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 0.1801 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 98
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:37:59.318 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 98
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:38:23.342 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 2.9922 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 98
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:38:23.400 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 98
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:43:29.361 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 1.6957 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:43:29.385 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:44:00.831 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 2.6990 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:44:00.922 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:44:51.342 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 2.7517 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:44:51.424 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:45:06.730 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 0.1581 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:45:06.733 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-04-28 03:53:56.689 [ERR] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP GET /weatherforecast responded 500 in 0.1179 ms
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2025-04-28 03:53:56.692 [ERR] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request.
System.Exception: 測試用故意拋出的錯誤！
   at Program.<>c.<<Main>$>b__0_2(HttpContext context) in /NET8_container/SerilogSample/Program.cs:line 100
   at lambda_method2(Closure, Object, HttpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
